<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.astroid.stijnjakobs</groupId>
        <artifactId>NetworkDataAPI-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>networkdataapi-bungee</artifactId>
    <packaging>jar</packaging>

    <name>NetworkDataAPI BungeeCord</name>
    <description>BungeeCord implementation for NetworkDataAPI</description>

    <dependencies>
        <!-- Core Module -->
        <dependency>
            <groupId>com.astroid.stijnjakobs</groupId>
            <artifactId>networkdataapi-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- BungeeCord API -->
        <dependency>
            <groupId>net.md-5</groupId>
            <artifactId>bungeecord-api</artifactId>
        </dependency>

        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>NetworkDataAPI-Bungee-${project.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <includes>
                                    <include>com.astroid.stijnjakobs:networkdataapi-core</include>
                                    <include>org.mongodb:*</include>
                                    <include>com.github.ben-manes.caffeine:*</include>
                                    <include>com.sparkjava:*</include>
                                    <include>com.google.code.gson:*</include>
                                    <include>org.slf4j:*</include>
                                    <include>javax.servlet:*</include>
                                    <include>org.eclipse.jetty:*</include>
                                    <include>org.eclipse.jetty.websocket:*</include>
                                </includes>
                            </artifactSet>
                            <relocations>
                                <relocation>
                                    <pattern>com.mongodb</pattern>
                                    <shadedPattern>com.astroid.stijnjakobs.networkdataapi.libs.mongodb</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.github.benmanes.caffeine</pattern>
                                    <shadedPattern>com.astroid.stijnjakobs.networkdataapi.libs.caffeine</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>spark</pattern>
                                    <shadedPattern>com.astroid.stijnjakobs.networkdataapi.libs.spark</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.google.gson</pattern>
                                    <shadedPattern>com.astroid.stijnjakobs.networkdataapi.libs.gson</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.eclipse.jetty</pattern>
                                    <shadedPattern>com.astroid.stijnjakobs.networkdataapi.libs.jetty</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>javax.servlet</pattern>
                                    <shadedPattern>com.astroid.stijnjakobs.networkdataapi.libs.servlet</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>

